name: Project_19
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.8.0
  - torchvision=0.23.0
  - torchaudio=2.8.0
  - cpuonly
  - tensorflow
  - scikit-learn=1.7.2
  - numpy>=1.21.0
  - pytest
  - flake8
  - rich
  - Pillow>=8.3.0
  - pip:
    - customtkinter>=5.2.0
    - opencv-python==4.12.0.88
    - keras-unet-collection==0.1.13
    - segmentation-models==1.0.1
    - segmentation-models-pytorch==0.5.0