name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # PyTorch and related packages with compatible versions
  - pytorch>=2.5.0,<2.7.0
  - torchvision>=0.20.0,<0.22.0
  - pytorch-cuda=12.1  # Replaces deprecated cudatoolkit
  # TensorFlow and Keras (corrected to existing version)
  - tensorflow>=2.16.0,<2.18.0
  # Scientific computing and ML
  - scikit-learn>=1.5.0,<1.7.0
  - numpy
  # Testing and linting tools (for your GitHub Actions)
  - pytest
  - flake8
  # pip packages that are not available in conda
  - pip:
    - opencv-python==4.12.0.88
    - keras-unet-collection==0.1.13
    - segmentation-models==1.0.1
    - segmentation-models-pytorch==0.5.0