name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # PyTorch and related packages
  - pytorch>=2.8.0
  - torchvision>=0.23.0
  - cudatoolkit  # Optional, only if you need GPU support
  # TensorFlow and Keras
  - tensorflow>=2.20.0
  # Scientific computing and ML
  - scikit-learn>=1.7.2
  - numpy
  # Testing and linting tools (for your GitHub Actions)
  - pytest
  - flake8
  # pip packages that are not available in conda
  - pip:
    - opencv-python==4.12.0.88
    - keras-unet-collection==0.1.13
    - segmentation-models==1.0.1
    - segmentation-models-pytorch==0.5.0